import jsPDF from 'jspdf';

export const exportClientPDF = (client, template, submission) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 0;

  // ─── Colors ───────────────────────────────────────────────
  const dark = [15, 15, 15];         // #0F0F0F
  const cyan = [108, 233, 254];      // #6CE9FE
  const white = [254, 254, 254];     // #FEFEFE
  const muted = [120, 120, 120];     // for secondary text
  const cardBg = [28, 28, 28];       // #1C1C1C
  const borderColor = [40, 40, 40];  // subtle border

  // ─── Helper: add new page if needed ──────────────────────
  const checkNewPage = (neededHeight) => {
    if (y + neededHeight > pageHeight - margin) {
      doc.addPage();
      drawPageBackground();
      y = margin + 10;
    }
  };

  // ─── Draw dark background ─────────────────────────────────
  const drawPageBackground = () => {
    doc.setFillColor(...dark);
    doc.rect(0, 0, pageWidth, pageHeight, 'F');
  };

  // ─── Draw header bar ──────────────────────────────────────
  const drawHeader = () => {
    // Header background
    doc.setFillColor(...cardBg);
    doc.rect(0, 0, pageWidth, 40, 'F');

    // Cyan accent line at top
    doc.setFillColor(...cyan);
    doc.rect(0, 0, pageWidth, 2, 'F');

    // Brand name
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.setTextColor(...cyan);
    doc.text('OnboardKit', margin, 18);

    // Document label
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...muted);
    doc.text('CLIENT PROJECT BRIEF', margin, 27);

    // Date on the right
    const date = new Date().toLocaleDateString('en-PH', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    doc.setFontSize(8);
    doc.setTextColor(...muted);
    doc.text(date, pageWidth - margin, 18, { align: 'right' });

    y = 52;
  };

  // ─── Draw footer ──────────────────────────────────────────
  const drawFooter = () => {
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFillColor(...cardBg);
      doc.rect(0, pageHeight - 14, pageWidth, 14, 'F');
      doc.setFillColor(...cyan);
      doc.rect(0, pageHeight - 14, pageWidth, 0.5, 'F');
      doc.setFontSize(7);
      doc.setTextColor(...muted);
      doc.text('Generated by OnboardKit', margin, pageHeight - 5);
      doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin, pageHeight - 5, { align: 'right' });
    }
  };

  // ─── Draw client info card ────────────────────────────────
  const drawClientCard = () => {
    checkNewPage(60);

    // Card background
    doc.setFillColor(...cardBg);
    doc.roundedRect(margin, y, contentWidth, 52, 3, 3, 'F');

    // Cyan left accent bar
    doc.setFillColor(...cyan);
    doc.roundedRect(margin, y, 3, 52, 1.5, 1.5, 'F');

    // Client name
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(...white);
    doc.text(client.name, margin + 12, y + 14);

    // Business
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...cyan);
    doc.text(client.business || '—', margin + 12, y + 24);

    // Email label + value
    doc.setFontSize(8);
    doc.setTextColor(...muted);
    doc.text('EMAIL', margin + 12, y + 35);
    doc.setTextColor(...white);
    doc.text(client.email || '—', margin + 12, y + 43);

    // Submitted label + value
    doc.setTextColor(...muted);
    doc.text('SUBMITTED', pageWidth - margin - 60, y + 35);
    doc.setTextColor(...white);
    const submittedDate = client.submittedAt
      ? new Date(client.submittedAt).toLocaleDateString('en-PH', {
          year: 'numeric', month: 'short', day: 'numeric',
        })
      : '—';
    doc.text(submittedDate, pageWidth - margin - 60, y + 43);

    y += 64;
  };

  // ─── Draw section title ───────────────────────────────────
  const drawSectionTitle = (text) => {
    checkNewPage(20);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(...cyan);
    doc.text(text.toUpperCase(), margin, y);

    // Underline
    doc.setDrawColor(...borderColor);
    doc.setLineWidth(0.3);
    doc.line(margin, y + 2, pageWidth - margin, y + 2);

    y += 10;
  };

  // ─── Draw one answer row ──────────────────────────────────
  const drawAnswerRow = (label, value, isEven) => {
    const lines = doc.splitTextToSize(value || '—', contentWidth - 60);
    const rowHeight = Math.max(16, lines.length * 6 + 10);

    checkNewPage(rowHeight);

    // Row background
    if (isEven) {
      doc.setFillColor(...cardBg);
      doc.rect(margin, y, contentWidth, rowHeight, 'F');
    }

    // Label
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...muted);
    doc.text(label, margin + 4, y + 7);

    // Value
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(...white);
    doc.text(lines, margin + 60, y + 7);

    // Bottom border
    doc.setDrawColor(...borderColor);
    doc.setLineWidth(0.2);
    doc.line(margin, y + rowHeight, margin + contentWidth, y + rowHeight);

    y += rowHeight;
  };

  // ─── Build the PDF ────────────────────────────────────────

  // Page 1 background
  drawPageBackground();
  drawHeader();
  drawClientCard();
  drawSectionTitle('Project Brief');

  if (submission && template) {
    template.fields.forEach((field, index) => {
      const answer = submission.answers?.[field.id] || '—';
      drawAnswerRow(field.label, answer, index % 2 === 0);
    });
  } else {
    checkNewPage(20);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(...muted);
    doc.text('No submission found for this client.', margin, y);
    y += 10;
  }

  drawFooter();

  // ─── Save the file ────────────────────────────────────────
  const fileName = `${client.name.replace(/\s+/g, '_')}_Brief_OnboardKit.pdf`;
  doc.save(fileName);
};